### PR TITLE
Move to RHEL UBI9 base image

### LINKED ISSUE #46: Move away from centos:7 base image
cvmfs-csi image is based on centos:7: https://github.com/cvmfs-contrib/cvmfs-csi/blob/release-v2.0/deployments/docker/Dockerfile.

Given EOL of the distribution and it containing pretty old packages, we need to move to something newer. To make things easier, we should pick a distro where CVMFS packages are available. See https://cernvm.cern.ch/fs/ for the list.

### PR DESCRIPTION
**Pull request by jcpunk**
Fixes #46

### CODE REVIEW

**Comment by gman0** [comment]
@jcpunk thanks for the contribution! I'm wondering if the CVMFS community could maintain a minimal image that would contain only the client. I'll ask around and then we can see if we move forward with this PR or there could be another way.

**Comment by jcpunk** [comment]
I would certainly love a much smaller container! My question is really on how much work it would be vs the simplicity of this approach - ie is there enough gain?

**Comment by jcpunk** [comment]
Just checking back in

**Comment by gman0** [comment]
Thanks, @jcpunk! We're still looking at https://github.com/cvmfs/cvmfs/issues/3114 as a base. I was busy with other tasks but will pick this up again. If the minimal image proves to be too complicated we'll most likely move to UBI.

**Comment by afgane** [comment]
https://github.com/cvmfs/cvmfs/issues/3114 hasn't moved in a while. Would it be OK to use this in the interim given it appears to be ready?

**Comment by jcpunk** [comment]
I'd be happy to have this merged until something else comes along.

**Comment by jcpunk** [comment]
Just checking back in....

**Comment by gman0** [comment]
Hi @jcpunk , thanks for reminding, and thanks for the contribution. Indeed, there was not much progress on the minimal image. Let's merge this and use UBI for now.

**Pull request merged**
