### PR TITLE
deploy(helm): configure seccomp profile for node & controller plugin

### PR DESCRIPTION
**Pull request by 1602077**
* deploy(helm): configured a seccomp profile of `RuntimeDefault` for `nodeplugin` daemonset and `controllerplugin` deployment.
* chore: formatted helm values file with `yamlfmt` for readability.

### CODE REVIEW

**Comment by 1602077** [comment]
Verified that this is working this morning by running the gitlab functional integration tests against a fresh cluster with cvmfs-csi installed manually.

**Comment by rochaporto** [comment]
LGTM. Needs a clear note in the release notes as well.

**Comment by 1602077** [comment]
@rochaporto great - can you take me through the release process next week please?

I also do not have permission to merge in once approved.

**Review by rochaporto — APPROVED** [review]
LGTM

**Comment by rochaporto** [comment]
The process for releasing is here:
https://github.com/cvmfs-contrib/cvmfs-csi/blob/master/CONTRIBUTING.md#releasing-a-new-version

**Pull request merged**
